variables:
  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - docker

maven-build:
  stage: build
  tags:
    - docker
  image: openjdk:17-jdk-slim
  script:
    - ./mvnw package -DskipTests
  artifacts:
    paths:
      - target/*.jar

unit-test:
  stage: test
  needs:
    - job: maven-build
  tags:
    - docker
  image: docker:latest
  services:
    - name: docker:dind
      command: [ "--tls=false" ]
  before_script:
    - apk add openjdk17-jdk
  script:
    - ./mvnw test

docker-build:
  stage: docker
  needs:
    - job: unit-test
  tags:
    - docker
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"
