DELETE FROM marks;
ALTER SEQUENCE marks_id_seq RESTART WITH 1;

DELETE FROM topics;
ALTER SEQUENCE topics_id_seq RESTART WITH 1;

DELETE FROM students_courses;

DELETE FROM courses;
ALTER SEQUENCE courses_id_seq RESTART WITH 1;

DELETE FROM students;
ALTER SEQUENCE students_id_seq RESTART WITH 1;

DELETE FROM teachers;
ALTER SEQUENCE teachers_id_seq RESTART WITH 1;

DELETE FROM schedules;
ALTER SEQUENCE schedules_id_seq RESTART WITH 1;

DELETE FROM groups;
ALTER SEQUENCE groups_id_seq RESTART WITH 1;

DELETE FROM managers;
ALTER SEQUENCE managers_id_seq RESTART WITH 1;

DELETE FROM lessons;
ALTER SEQUENCE lessons_id_seq RESTART WITH 1;

DELETE FROM study_days;
ALTER SEQUENCE study_days_id_seq RESTART WITH 1;
