INSERT INTO courses (course_name, course_description, teacher_id, created_at, updated_at)
VALUES ('Python Programming', '“Python Programming” is an introductory course that covers Python syntax, data structures, and libraries, suitable for both beginners and experienced programmers.', 2, '2023-09-01 11:22:03+00', '2023-09-01 11:22:03+00'),
       ('Marketing Basics', '“Marketing Basics” is a course that provides an overview of key concepts and techniques used in marketing. It covers topics such as market research, consumer behavior, product development, and promotional strategies', 8, '2023-09-02 00:57:14+00', '2023-09-02 00:57:14+00'),
       ('Graphic Design', '“Graphic Design” is a course that explores the key concepts of visual communication, including typography, color theory, and layout design. Suitable for beginners and those looking to refresh their skills.', 3, '2023-09-02 13:32:25+00', '2023-09-02 13:32:25+00'),
       ('Web Development', '“Web Development” is a course that introduces the fundamentals of creating websites, including HTML, CSS, and JavaScript basics. It’s ideal for those interested in crafting user-friendly, aesthetically pleasing online platforms.', 3, '2023-09-03 03:07:36+00', '2023-09-03 03:07:36+00'),
       ('Photography Basics', '“Photography Basics” is a course that introduces the fundamentals of photography, including understanding camera settings, composition, lighting, and post-processing techniques. Ideal for beginners and hobbyists.', 7, '2023-09-03 15:42:47+00', '2023-09-03 15:42:47+00'),
       ('Spanish Learning', '“Spanish Learning” is a course that offers a comprehensive introduction to the Spanish language, covering basic grammar, vocabulary, pronunciation, and conversational skills. Ideal for beginners and those looking to brush up on their skills.', 5, '2023-09-04 05:17:58+00', '2023-09-04 05:17:58+00'),
       ('Accounting Basics', '“Accounting Basics” is a course that provides an introduction to the fundamental principles and practices of accounting, covering topics such as financial statements, bookkeeping, and budgeting. Ideal for those new to accounting or seeking a refresher.', 10, '2023-09-04 17:53:09+00', '2023-09-04 17:53:09+00'),
       ('Guitar Basics', '“Guitar Basics” is a course that introduces the fundamentals of playing the guitar, including understanding guitar anatomy, basic chords, strumming patterns, and simple melodies. Ideal for beginners and those looking to brush up on their skills.', 9, '2023-09-05 07:28:20+00', '2023-09-05 07:28:20+00'),
       ('French Learning', '“French Learning” is a course that provides a comprehensive introduction to the French language, covering essential grammar, vocabulary, pronunciation, and conversational skills. It’s perfect for beginners and those wishing to improve their French.', 5, '2023-09-05 20:03:31+00', '2023-09-05 20:03:31+00'),
       ('Japanese Cooking', '“Japanese Cooking” is a course that introduces the fundamentals of Japanese cuisine, including the preparation of traditional dishes, understanding unique ingredients, and mastering essential cooking techniques. Ideal for food enthusiasts and aspiring chefs.', 6, '2023-09-06 09:38:42+00', '2023-09-06 09:38:42+00'),
       ('Piano Basics', '“Piano Basics” is a course that introduces the fundamentals of playing the piano, including understanding piano anatomy, basic chords, reading sheet music, and simple melodies. Ideal for beginners and those looking to brush up on their skills.', 9, '2023-09-06 22:13:53+00', '2023-09-06 22:13:53+00'),
       ('Digital Marketing', '“Digital Marketing” is a course that provides an overview of online marketing strategies, including SEO, social media marketing, email marketing, and content marketing. Ideal for those looking to expand their marketing skills in the digital realm.', 8, '2023-09-07 11:49:04+00', '2023-09-07 11:49:04+00'),
       ('Drawing Basics', '“Drawing Basics” is a course that introduces the fundamentals of drawing, including understanding shapes, shading techniques, perspective, and composition. It’s perfect for beginners and those wishing to improve their drawing skills.', 7, '2023-09-08 01:24:15+00', '2023-09-08 01:24:15+00'),
       ('German Learning', '“German Learning” is a course that provides a comprehensive introduction to the German language, covering essential grammar, vocabulary, pronunciation, and conversational skills. It’s perfect for beginners and those wishing to improve their German.', 5, '2023-09-09 13:46:17+00', '2023-09-09 13:46:17+00'),
       ('French Cooking', '“French Cooking” is a course that introduces the art of French cuisine, covering traditional recipes, cooking techniques, and the cultural significance of various dishes. Ideal for aspiring chefs and food enthusiasts.', 6, '2023-09-10 08:08:55+00', '2023-09-10 08:08:55+00'),
       ('Social Media Marketing', '“Social Media Marketing” is a course that covers strategies for promoting products or services on social media platforms, including content creation, audience engagement, and analytics. Ideal for those looking to expand their digital marketing skills.', 8, '2023-09-11 02:31:33+00', '2023-09-11 02:31:33+00'),
       ('Italian Learning', '“Italian Learning” is a course that offers a comprehensive introduction to the Italian language, covering basic grammar, vocabulary, pronunciation, and conversational skills. Ideal for beginners and those looking to brush up on their skills.', 5, '2023-09-11 20:54:11+00', '2023-09-11 20:54:11+00'),
       ('Chinese Cooking', '“Chinese Cooking” is a course that introduces the fundamentals of Chinese cuisine, including the preparation of traditional dishes, understanding unique ingredients, and mastering essential cooking techniques. Ideal for food enthusiasts and aspiring chefs.', 6, '2023-09-12 15:16:49+00', '2023-09-12 15:16:49+00'),
       ('Violin Basics', '“Violin Basics” is a course that introduces the fundamentals of playing the violin, including understanding violin anatomy, basic notes, reading sheet music, and simple melodies. Ideal for beginners and those looking to brush up on their skills.', 9, '2023-09-13 09:39:27+00', '2023-09-13 09:39:27+00'),
       ('SEO Introduction', '“SEO Introduction” is a comprehensive course that delves into the essentials of Search Engine Optimization, providing key strategies for enhancing website visibility and boosting search engine rankings.', 10, '2023-09-14 04:02:05+00', '2023-09-14 04:02:05+00'),
       ('Graffiti Basics', '“Graffiti Basics” is an immersive course that explores the fundamental techniques and creative aspects of graffiti art, fostering artistic expression through vibrant street art.', 7, '2023-09-14 22:24:43+00', '2023-09-14 22:24:43+00'),
       ('Indian Cooking', '“Indian Cooking” is a detailed course that unveils the rich flavors and diverse techniques of traditional Indian cuisine, guiding learners to create authentic Indian dishes.', 6, '2023-09-15 16:47:21+00', '2023-09-15 16:47:21+00'),
       ('Advertising Business', '“Advertising Business” is a comprehensive course that dives into the intricacies of business advertising, offering key strategies and techniques for success in today’s competitive market.', 10, '2023-09-16 11:09:59+00', '2023-09-16 11:09:59+00'),
       ('Applied Mathematics', '“Applied Mathematics” is a course that offers a deep dive into the practical application of mathematical concepts in real-world scenarios, fostering analytical thinking and problem-solving skills.', 4, '2023-09-17 05:32:37+00', '2023-09-17 05:32:37+00'),
       ('Electronics & Circuitry', '“Electronics & Circuitry” is a course that provides a comprehensive understanding of the principles of electronics and circuit design, equipping learners with the skills to create and troubleshoot electronic devices.', 1, '2023-09-17 23:55:15+00', '2023-09-17 23:55:15+00'),
       ('AutoCAD Modeling', '“AutoCAD Modeling” is a course that provides hands-on experience in creating detailed 3D models using AutoCAD, a leading software in the field of computer-aided design.', 4, '2023-09-18 12:11:00+00', '2023-09-18 12:11:00+00'),
       ('MatLab Introduction', '“MatLab Introduction” is a course that provides a comprehensive introduction to MatLab, a high-level programming language used for numerical computation and visualization.', 2, '2023-09-19 05:16:59+00', '2023-09-19 05:16:59+00'),
       ('STM32 Embedded Development', '“STM32 Embedded Development” is a course that offers a deep understanding of STM32 microcontrollers and teaches practical skills in embedded system development using STM32.', 1, '2023-09-19 22:22:58+00', '2023-09-19 22:22:58+00'),
       ('UI/UX Design Basics', '“UI/UX Design Basics” is a course that introduces the fundamental principles of User Interface and User Experience design, equipping learners with the skills to create intuitive and user-friendly digital interfaces.', 3, '2023-09-20 15:28:57+00', '2023-09-20 15:28:57+00'),
       ('Networks and Communication', '“Networks and Communication” is a course that provides a comprehensive understanding of the principles and technologies used in network communication, equipping learners with the skills to design, implement, and troubleshoot network systems.', 1, '2023-09-21 08:34:56+00', '2023-09-21 08:34:56+00');


INSERT INTO topics (topic_name, topic_description, topic_order, course_id)
VALUES ('Python Syntax', 'This topic covers the basic syntax of Python, including data types, variables, loops, and functions.', 1, 1),
       ('Python Data Structures', 'This topic delves into Python data structures such as lists, tuples, sets, and dictionaries, and how to use them effectively.', 2, 1),
       ('Python Libraries', 'This topic provides an overview of popular Python libraries such as NumPy, Pandas, and Matplotlib, and their applications.', 3, 1),
       ('Object-Oriented Programming in Python', 'This topic introduces the concept of Object-Oriented Programming (OOP) in Python, covering classes, objects, inheritance, and more.', 4, 1),
       ('Python for Data Analysis', 'This topic explores how Python can be used for data analysis, including data manipulation, data visualization, and basic statistical analysis.', 5, 1),

       ('Market Research', 'This topic covers the fundamentals of market research, including qualitative and quantitative research methods, data analysis, and interpretation.', 1, 2),
       ('Consumer Behavior', 'This topic delves into the study of consumer behavior, exploring the psychological, social, and economic factors that influence consumer decisions.', 2, 2),
       ('Product Development', 'This topic provides an overview of the product development process, from idea generation and concept development to market testing and product launch.', 3, 2),
       ('Promotional Strategies', 'This topic explores various promotional strategies used in marketing, including advertising, sales promotion, public relations, and direct marketing.', 4, 2),
       ('Digital Marketing', 'This topic introduces the concept of digital marketing, covering topics such as search engine optimization, social media marketing, and email marketing.', 5, 2),

       ('Typography', 'This topic covers the art and technique of arranging type, including font styles, line spacing, and letter spacing.', 1, 3),
       ('Color Theory', 'This topic explores the science and art of color theory, including the color wheel, color harmony, and the psychological effects of color.', 2, 3),
       ('Layout Design', 'This topic provides an overview of layout design principles, including balance, alignment, contrast, and hierarchy.', 3, 3),
       ('Branding and Identity', 'This topic delves into the role of graphic design in branding and identity, including logo design, color palettes, and brand guidelines.', 4, 3),
       ('Digital Tools for Graphic Design', 'This topic introduces various digital tools used in graphic design, such as Adobe Illustrator, Photoshop, and InDesign.', 5, 3),

       ('HTML Basics', 'This topic covers the basics of HTML, including tags, elements, attributes, and the document structure.', 1, 4),
       ('CSS Fundamentals', 'This topic delves into the fundamentals of CSS, including selectors, properties, values, and the box model.', 2, 4),
       ('JavaScript Essentials', 'This topic provides an overview of JavaScript, covering syntax, data types, functions, and event handling.', 3, 4),
       ('Responsive Web Design', 'This topic explores the principles of responsive web design, including flexible layouts, media queries, and responsive images.', 4, 4),

       ('Understanding Camera Settings', 'This topic covers the basics of camera settings, including aperture, shutter speed, ISO, and white balance.', 1, 5),
       ('Composition Techniques', 'This topic delves into composition techniques in photography, such as the rule of thirds, leading lines, and depth of field.', 2, 5),
       ('Lighting Fundamentals', 'This topic provides an overview of lighting in photography, covering natural light, artificial light, and how to manipulate light for different effects.', 3, 5),
       ('Post-Processing Techniques', 'This topic introduces post-processing techniques in photography, including cropping, color correction, and the use of filters.', 4, 5),

       ('Spanish Grammar', 'This topic covers the basics of Spanish grammar, including verb conjugations, sentence structure, and the use of tenses.', 1, 6),
       ('Spanish Vocabulary', 'This topic delves into Spanish vocabulary, covering common words and phrases used in daily conversation, as well as specific terminology for various situations.', 2, 6),
       ('Spanish Pronunciation', 'This topic provides an overview of Spanish pronunciation, including the sounds of vowels and consonants, accent rules, and pronunciation tips.', 3, 6),
       ('Conversational Spanish', 'This topic introduces conversational Spanish, covering common phrases, etiquette, and cultural nuances in Spanish-speaking countries.', 4, 6),

       ('Financial Statements', 'This topic covers the basics of financial statements, including the balance sheet, income statement, and cash flow statement.', 1, 7),
       ('Bookkeeping', 'This topic delves into the fundamentals of bookkeeping, including recording financial transactions, posting debits and credits, and maintaining ledgers.', 2, 7),
       ('Budgeting', 'This topic provides an overview of budgeting in accounting, covering the process of preparing budgets, variance analysis, and the role of budgets in decision making.', 3, 7),
       ('Cost Accounting', 'This topic introduces cost accounting, a method of accounting that aims to capture a companys costs of production by assessing the input costs of each step of production.', 4, 7),
       ('Tax Accounting', 'This topic explores tax accounting, a structure of accounting methods focused on taxes rather than the appearance of public financial statements.', 5, 7),

       ('Understanding Guitar Anatomy', 'This topic covers the different parts of the guitar and their functions, including the body, neck, fretboard, strings, and more.', 1, 8),
       ('Basic Chords', 'This topic introduces the basic chords used in guitar playing, including major, minor, and seventh chords.', 2, 8),
       ('Strumming Patterns', 'This topic delves into different strumming patterns used in various music styles, and how to practice them effectively.', 3, 8),
       ('Reading Guitar Tabs', 'This topic provides an overview of how to read guitar tabs, a form of musical notation for guitar.', 4, 8),
       ('Simple Melodies', 'This topic guides learners through playing simple melodies on the guitar, helping to develop their musical ear and finger dexterity.', 5, 8),

       ('French Grammar', 'This topic covers the basics of French grammar, including verb conjugations, sentence structure, and the use of tenses.', 1, 9),
       ('French Vocabulary', 'This topic delves into French vocabulary, covering common words and phrases used in daily conversation, as well as specific terminology for various situations.', 2, 9),
       ('French Pronunciation', 'This topic provides an overview of French pronunciation, including the sounds of vowels and consonants, accent rules, and pronunciation tips.', 3, 9),
       ('Conversational French', 'This topic introduces conversational French, covering common phrases, etiquette, and cultural nuances in French-speaking countries.', 4, 9),
       ('French for Travel', 'This topic focuses on French language skills specifically for travel, including essential phrases and cultural etiquette.', 5, 9),

       ('Traditional Dishes', 'This topic covers the preparation of traditional Japanese dishes, including sushi, tempura, and ramen.', 1, 10),
       ('Unique Ingredients', 'This topic delves into unique ingredients used in Japanese cuisine, such as wasabi, miso, and matcha.', 2, 10),
       ('Cooking Techniques', 'This topic provides an overview of essential cooking techniques in Japanese cuisine, including grilling, steaming, and simmering.', 3, 10),
       ('Japanese Kitchen Tools', 'This topic introduces various kitchen tools commonly used in Japanese cooking, such as the suribachi and surikogi (mortar and pestle), oroshigane (grater), and hangiri (sushi rice tub).', 4, 10),

       ('Understanding Piano Anatomy', 'This topic covers the different parts of the piano and their functions, including the keys, pedals, and strings.', 1, 11),
       ('Basic Chords', 'This topic introduces the basic chords used in piano playing, including major, minor, and seventh chords.', 2, 11),
       ('Reading Sheet Music', 'This topic provides an overview of how to read sheet music, including understanding musical notes, rhythms, and dynamics.', 3, 11),
       ('Simple Melodies', 'This topic guides learners through playing simple melodies on the piano, helping to develop their musical ear and finger dexterity.', 4, 11),

       ('SEO Strategies', 'This topic covers the fundamentals of Search Engine Optimization (SEO), including keyword research, on-page optimization, and link building strategies.', 1, 12),
       ('Social Media Marketing', 'This topic delves into the use of social media platforms for marketing, including content creation, audience engagement, and analytics.', 2, 12),
       ('Email Marketing', 'This topic provides an overview of email marketing, covering topics such as crafting effective emails, building an email list, and tracking email performance.', 3, 12),
       ('Content Marketing', 'This topic introduces the concept of content marketing, discussing how to create and distribute valuable content to attract and retain a clearly-defined audience.', 4, 12),

       ('Understanding Shapes', 'This topic covers the basics of understanding shapes, including how to draw basic shapes and how they form the basis of complex drawings.', 1, 13),
       ('Shading Techniques', 'This topic delves into different shading techniques used in drawing, including hatching, cross-hatching, stippling, and blending.', 2, 13),
       ('Perspective Drawing', 'This topic provides an overview of perspective drawing, covering one-point, two-point, and three-point perspectives.', 3, 13),
       ('Composition in Drawing', 'This topic introduces the concept of composition in drawing, discussing how to arrange elements on the page to create a balanced and interesting artwork.', 4, 13),

       ('German Grammar', 'This topic covers the basics of German grammar, including verb conjugations, sentence structure, and the use of tenses.', 1, 14),
       ('German Vocabulary', 'This topic delves into German vocabulary, covering common words and phrases used in daily conversation, as well as specific terminology for various situations.', 2, 14),
       ('German Pronunciation', 'This topic provides an overview of German pronunciation, including the sounds of vowels and consonants, accent rules, and pronunciation tips.', 3, 14),
       ('Conversational German', 'This topic introduces conversational German, covering common phrases, etiquette, and cultural nuances in German-speaking countries.', 4, 14),

       ('Traditional French Recipes', 'This topic covers traditional French recipes, including coq au vin, bouillabaisse, and ratatouille.', 1, 15),
       ('French Cooking Techniques', 'This topic delves into various cooking techniques used in French cuisine, such as sautéing, roasting, and braising.', 2, 15),
       ('French Ingredients', 'This topic provides an overview of common ingredients used in French cooking, such as herbs, cheeses, and wines.', 3, 15),
       ('French Kitchen Tools', 'This topic introduces various kitchen tools commonly used in French cooking, such as the mandoline, the chinois, and the chef’s knife.', 4, 15),

       ('Content Creation', 'This topic covers the process of creating engaging and relevant content for social media platforms.', 1, 16),
       ('Audience Engagement', 'This topic delves into strategies for engaging with your audience on social media, including responding to comments, hosting live sessions, and using interactive features.', 2, 16),
       ('Social Media Analytics', 'This topic provides an overview of social media analytics, including how to track engagement, reach, and conversions.', 3, 16),
       ('Social Media Advertising', 'This topic introduces the concept of social media advertising, covering ad formats, targeting options, and budgeting.', 4, 16),

       ('Italian Grammar', 'This topic covers the basics of Italian grammar, including verb conjugations, sentence structure, and the use of tenses.', 1, 17),
       ('Italian Vocabulary', 'This topic delves into Italian vocabulary, covering common words and phrases used in daily conversation, as well as specific terminology for various situations.', 2, 17),
       ('Italian Pronunciation', 'This topic provides an overview of Italian pronunciation, including the sounds of vowels and consonants, accent rules, and pronunciation tips.', 3, 17),
       ('Conversational Italian', 'This topic introduces conversational Italian, covering common phrases, etiquette, and cultural nuances in Italian-speaking countries.', 4, 17),
       ('Italian for Travel', 'This topic focuses on Italian language skills specifically for travel, including essential phrases and cultural etiquette.', 5, 17),

       ('Traditional Chinese Recipes', 'This topic covers traditional Chinese recipes, including dumplings, Peking duck, and hot pot.', 1, 18),
       ('Chinese Cooking Techniques', 'This topic delves into various cooking techniques used in Chinese cuisine, such as stir-frying, steaming, and roasting.', 2, 18),
       ('Chinese Ingredients', 'This topic provides an overview of common ingredients used in Chinese cooking, such as soy sauce, ginger, and bok choy.', 3, 18),
       ('Chinese Kitchen Tools', 'This topic introduces various kitchen tools commonly used in Chinese cooking, such as the wok, cleaver, and bamboo steamer.', 4, 18),
       ('Regional Chinese Cuisines', 'This topic explores the diverse regional cuisines of China, including Sichuan, Cantonese, and Shandong cuisines.', 5, 18),

       ('Understanding Violin Anatomy', 'This topic covers the different parts of the violin and their functions, including the strings, bow, and fingerboard.', 1, 19),
       ('Basic Notes and Scales', 'This topic introduces the basic notes and scales used in violin playing, including major, minor, and chromatic scales.', 2, 19),
       ('Reading Sheet Music', 'This topic provides an overview of how to read sheet music, including understanding musical notes, rhythms, and dynamics.', 3, 19),
       ('Simple Melodies', 'This topic guides learners through playing simple melodies on the violin, helping to develop their musical ear and finger dexterity.', 4, 19),
       ('Violin Maintenance', 'This topic covers the basics of violin maintenance, including tuning, cleaning, and string replacement.', 5, 19),

       ('Understanding SEO', 'This topic provides a comprehensive overview of Search Engine Optimization (SEO), including its importance and benefits.', 1, 20),
       ('Keyword Research', 'This topic delves into the process of keyword research, a fundamental aspect of SEO that involves identifying popular words and phrases people enter into search engines.', 2, 20),
       ('On-Page SEO', 'This topic covers on-page SEO strategies, which involve optimizing individual webpages in order to rank higher and earn more relevant traffic in search engines.', 3, 20),
       ('Off-Page SEO', 'This topic introduces off-page SEO, which refers to actions taken outside of your own website to impact your rankings within search engine results pages.', 4, 20),
       ('Technical SEO', 'This topic explores technical SEO, which covers website and server optimizations that help search engine spiders crawl and index your site more effectively.', 5, 20),

       ('Graffiti Styles', 'This topic covers various styles of graffiti, including throw-ups, pieces, and stencils.', 1, 21),
       ('Graffiti Techniques', 'This topic delves into different techniques used in graffiti, such as can control, flaring, and fading.', 2, 21),
       ('Graffiti Tools and Materials', 'This topic provides an overview of the tools and materials used in graffiti, including spray cans, markers, and caps.', 3, 21),
       ('Graffiti History and Culture', 'This topic explores the history and culture of graffiti, including its origins, evolution, and influence on urban culture.', 4, 21),
       ('Graffiti and the Law', 'This topic discusses the legal aspects of graffiti, including laws against vandalism, penalties, and the debate over graffiti as art or crime.', 5, 21),

       ('Traditional Indian Recipes', 'This topic covers traditional Indian recipes, including biryani, samosa, and butter chicken.', 1, 22),
       ('Indian Spices and Ingredients', 'This topic delves into various spices and ingredients used in Indian cooking, such as turmeric, cumin, and garam masala.', 2, 22),
       ('Indian Cooking Techniques', 'This topic provides an overview of cooking techniques commonly used in Indian cuisine, such as tempering, roasting, and slow-cooking.', 3, 22),
       ('Regional Indian Cuisines', 'This topic explores the diverse regional cuisines of India, including Punjabi, Bengali, and South Indian cuisines.', 4, 22),
       ('Healthy Indian Cooking', 'This topic introduces the concept of healthy Indian cooking, discussing how to create nutritious and balanced meals using Indian recipes.', 5, 22),

       ('Advertising Strategies', 'This topic covers various advertising strategies, including targeting, segmentation, and positioning.', 1, 23),
       ('Types of Advertising', 'This topic delves into different types of advertising, such as print, digital, outdoor, and broadcast advertising.', 2, 23),
       ('Creating Effective Advertisements', 'This topic provides an overview of how to create effective advertisements, including understanding the target audience, crafting compelling messages, and choosing the right visuals.', 3, 23),
       ('Advertising Laws and Ethics', 'This topic introduces the laws and ethics of advertising, discussing issues such as truth in advertising, privacy, and social responsibility.', 4, 23),
       ('Measuring Advertising Effectiveness', 'This topic explores how to measure the effectiveness of advertising campaigns, including methods such as sales tracking, customer surveys, and digital analytics.', 5, 23),

       ('Linear Algebra', 'This topic covers the fundamentals of linear algebra, including matrices, vectors, and linear transformations.', 1, 24),
       ('Calculus', 'This topic delves into the principles of calculus, including differentiation, integration, and limits.', 2, 24),
       ('Probability and Statistics', 'This topic provides an overview of probability and statistics, covering topics such as random variables, probability distributions, and statistical inference.', 3, 24),
       ('Differential Equations', 'This topic introduces differential equations, discussing how to solve ordinary and partial differential equations.', 4, 24),
       ('Numerical Methods', 'This topic explores numerical methods, including techniques for numerical integration, interpolation, and solving systems of equations.', 5, 24),

       ('Basic Electronic Components', 'This topic covers the basics of electronic components, including resistors, capacitors, diodes, and transistors.', 1, 25),
       ('Circuit Analysis', 'This topic delves into the principles of circuit analysis, including Ohm’s Law, Kirchhoff’s Laws, and Thevenin’s Theorem.', 2, 25),
       ('Digital Electronics', 'This topic provides an overview of digital electronics, covering topics such as logic gates, flip-flops, and digital circuits.', 3, 25),
       ('Analog Electronics', 'This topic introduces analog electronics, discussing concepts such as amplifiers, oscillators, and analog filters.', 4, 25),
       ('Microcontrollers and Programming', 'This topic explores the use of microcontrollers in electronic circuits, including programming, interfacing, and applications.', 5, 25),

       ('2D Drafting', 'This topic covers the basics of 2D drafting in AutoCAD, including drawing shapes, adding dimensions, and using layers.', 1, 26),
       ('3D Modeling', 'This topic delves into 3D modeling in AutoCAD, covering topics such as creating solid primitives, modifying 3D objects, and using 3D viewing techniques.', 2, 26),
       ('Rendering and Visualization', 'This topic provides an overview of rendering and visualization in AutoCAD, discussing how to add materials, lights, and cameras to a 3D model.', 3, 26),
       ('AutoCAD Customization', 'This topic introduces AutoCAD customization, covering topics such as creating custom command aliases and tool palettes.', 4, 26),
       ('Collaboration and Sharing', 'This topic explores collaboration and sharing in AutoCAD, including how to share drawings online, collaborate in real time, and use cloud storage.', 5, 26),

       ('MatLab Basics', 'This module introduces the basics of programming in MatLab, including syntax, operations, and data structures.', 1, 27),
       ('Data Visualization in MatLab', 'This module teaches how to use MatLab for data visualization, including creating plots and charts.', 2, 27),
       ('Signal Processing in MatLab', 'This module focuses on using MatLab for signal processing, including filtering, modulation, and signal recovery.', 3, 27),
       ('Mathematical Modeling in MatLab', 'This module demonstrates how to use MatLab for mathematical modeling, including solving equations and optimization.', 4, 27),
       ('User Interface Development in MatLab', 'This module teaches how to create a graphical user interface in MatLab for better user interaction.', 5, 27),

       ('STM32 Architecture', 'This module introduces the architecture of STM32 microcontrollers, including its core and peripherals.', 1, 28),
       ('STM32 Programming Basics', 'This module covers the basics of programming STM32 microcontrollers, including syntax, operations, and data structures.', 2, 28),
       ('Peripheral Interfacing with STM32', 'This module focuses on interfacing various peripherals with STM32 microcontrollers, including sensors, displays, and communication modules.', 3, 28),
       ('Real-Time Operating Systems for STM32', 'This module introduces real-time operating systems for STM32 microcontrollers, including FreeRTOS and ChibiOS.', 4, 28),
       ('Advanced STM32 Development', 'This module covers advanced topics in STM32 development, including low-power modes, advanced peripheral usage, and firmware upgrades.', 5, 28),

       ('Principles of UI Design', 'This module introduces the fundamental principles of user interface design, including layout, color theory, typography, and more.', 1, 29),
       ('Principles of UX Design', 'This module covers the basics of user experience design, including user research, user personas, user journey mapping, and usability testing.', 2, 29),
       ('Prototyping and Wireframing', 'This module teaches how to create wireframes and prototypes for digital products using tools like Sketch, Figma, and Adobe XD.', 3, 29),
       ('Interaction Design', 'This module focuses on designing interactive elements of digital products, including animations, transitions, and micro-interactions.', 4, 29),
       ('Design Systems and Style Guides', 'This module covers the creation and maintenance of design systems and style guides to ensure consistency in digital products.', 5, 29),

       ('Network Fundamentals', 'This module introduces the fundamental concepts of networks and communication, including network topologies, protocols, and models.', 1, 30),
       ('Data Communication', 'This module covers the basics of data communication, including signal transmission, encoding methods, and error detection and correction.', 2, 30),
       ('Internet Protocols', 'This module focuses on the Internet Protocol Suite, including IP, TCP, UDP, and application layer protocols like HTTP, FTP, and SMTP.', 3, 30),
       ('Wireless Networks', 'This module introduces wireless networks, including Wi-Fi, Bluetooth, cellular networks, and emerging wireless technologies.', 4, 30),
       ('Network Security', 'This module covers network security concepts, including encryption, firewalls, intrusion detection systems, and secure network design.', 5, 30);
